### ISSUE TITLE
calc(calc) doesn't work 

### ISSUE THREAD

**Issue by zavr-1** [artdecocode/closure-stylesheets-1#2]
```css
.input.is-rounded {
  border-radius: 290486px;
  padding-left: calc(calc(0.75em - 1px) + 0.375em);
  padding-right: calc(calc(0.75em - 1px) + 0.375em);
}
```
